using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Tilemaps;
using System.Collections;
using System.Linq;
using System;
using NUnit.Framework;
using UnityEngine.UIElements;
using UnityEngine.InputSystem.Utilities;
using Unity.Mathematics;
using System.Security.Principal;
using UnityEditor;

/* DONE list...
-- DONE; Round world including fast oval room bounds checking
-- DONE: Nested Perlin / Stacked Perlin
-- DONE: Filter small wall areas
-- DONE: 3D walls
-- DONE: Code cleanup for organization and optimization
-- DONE: Use Rooms list to draw 3D, not a copy of the 2D map.
   (allows corridors above/below rooms)
-- DONE: Clamp ramp slopes at 1.
-- DONE: Don't draw diagonals when 3 walls on one tile.

   TODO list...
-- Simplex Noise
-- Presets of interesting dungeons - menu or random selection
-- Adding extra corridors to break up tree
-- DONE: Smart hash calculations
-- More tile types: stairs, doors, traps (with properties)
-- Fix early regeneration button (abort in-progress)
-- Fix pulldown after recompile
-- DONE: Don't show build progress option implementation
-- Enforce minimum width room connectivity
-- Walkthrough capability
-- Camera flight controls
-- DONE: Reorganize files
-- DONE: Use more intelligent yielding to accomplish more each refresh.
-- Multi-layer map generation
-- PARTIALLY: Fix corridors between stacked rooms
-- Ceiling hight minimum and room merging
-- Gently sloping floors without stairs (perlin heights)
-- DONE: Change long 3D routines to coroutines.
 */

// Master Dungeon Generation Class...
public partial class DungeonGenerator : MonoBehaviour
{

    //    public tilemap tilemap;
    //    public TileBase floorTile;
    //    public TileBase wallTile;
    // ---------------------------------------------------------------
    // Different ways to store the map: room(list of points) and mapArray (grid of bytes)
    //public List<Room> rooms = new(); // Master List of rooms including list of points and metadata

    public List<RectInt> room_rects = new(); // List of RectInt rooms for ScatterRooms
    public List<int> room_rects_heights = new(); // List of heights for each room rectangle
    public List<Color> room_rects_color = new();


    // Reference to each class is maintained here
    public Door doorclass;
    public DungeonSettings cfg;
    public BottomBanner bottomBanner;
    public TimeManager timeManager;


    // ------------------------------------- //
    // Start is called by Unity before the first frame update
    public void Start()
    {
        // Initialize randomizer either with preselected seed, or one generated by clock
        if (cfg.randomizeSeed) cfg.seed = (int)DateTime.Now.Ticks;
        UnityEngine.Random.InitState(cfg.seed);
        Debug.Log("DungeonGenerator starting with seed: " + cfg.seed);

        // Start the fun...

        StartCoroutine(RegenerateDungeon(null));
    }

    // RegenerateDungeon is the main coroutine that handles dungeon generation.
    // It orchestrates the various steps involved in creating the dungeon layout.
    // Step 0: Select settings
    // Step 1: Initialize the dungeon
    // Step 2: Place rooms (ScatterRooms or CellularAutomata)
    // Step 3: Convert rooms to a list of floor tiles (ConvertRectToRoomPoints or findRoomTiles for CA)
    // Step 4: Combine overlapping rooms (MergeOverlappingRooms)
    // Step 5: Connect rooms by corridors (DrawCorridors)

    // Other routines:
    //  Draw Map by Rooms
    //  Draw Walls

    public IEnumerator RegenerateDungeon(TimeTask tm = null)
    {
        bool local_tm = false;
        if (tm == null) { tm = TimeManager.Instance.BeginTask("RegenerateDungeon"); local_tm = true; }
        try
        {
            room_rects = new List<RectInt>(); // Clear the list of room rectangles
            mapHeights = new int[cfg.mapWidth, cfg.mapHeight];
            Destroy3D();
            if (tm.IfYield()) yield return null;     // cooperative yield decision
            BottomBanner.Show("Generating dungeon...");

            // Step 0: Select settings
            switch (cfg.RoomAlgorithm) // Change this to select different algorithms
            {
                case DungeonSettings.RoomAlgorithm_e.Scatter_Overlap:
                    cfg.generateOverlappingRooms = true;
                    cfg.useCellularAutomata = false;
                    cfg.useScatterRooms = true;
                    //tavern.enabled = false;
                    break;
                case DungeonSettings.RoomAlgorithm_e.Scatter_NoOverlap:
                    cfg.generateOverlappingRooms = false;
                    cfg.useCellularAutomata = false;
                    cfg.useScatterRooms = true;
                    //tavern.enabled = false;
                    break;
                case DungeonSettings.RoomAlgorithm_e.CellularAutomata:
                    cfg.generateOverlappingRooms = false;
                    cfg.useCellularAutomata = true;
                    cfg.useScatterRooms = false;
                    cfg.usePerlin = false; // Disable Perlin for CA
                    //tavern.enabled = false;
                    break;
                case DungeonSettings.RoomAlgorithm_e.CellularAutomataPerlin:
                    cfg.generateOverlappingRooms = false;
                    cfg.useCellularAutomata = true;
                    cfg.useScatterRooms = false;
                    cfg.usePerlin = true; // Enable Perlin for CA
                    //tavern.enabled = false;
                    break;
                case DungeonSettings.RoomAlgorithm_e.Tavern:
                    cfg.generateOverlappingRooms = false;
                    //tavern.enabled = true;
                    cfg.useCellularAutomata = false;
                    cfg.useScatterRooms = false;
                    break;
            }

            BottomBanner.Show("Initialize dungeon...");


            // ===== Step 1. Initialize the dungeon
            tilemap.ClearAllTiles();
            rooms.Clear();
            map = new byte[cfg.mapWidth, cfg.mapHeight];
            FillVoidToWalls(map);
            yield return tm.YieldOrDelay(cfg.stepDelay);

            // ===== Step 2. Place rooms

            // TAVERN
//            if (tavern.enabled)
//            {
//                yield return StartCoroutine(BuildTavern(tm: null));
//            }

            if (cfg.useCellularAutomata) // Cellular Automata generation
            {
                BottomBanner.Show("Cellular Automata cavern generation iterating...");
                yield return StartCoroutine(RunCellularAutomation(tm: null));
                DrawWalls();
            }
            if (cfg.useScatterRooms)
            {
                BottomBanner.Show("Scattering rooms...");
                yield return StartCoroutine(ScatterRooms(tm: null));
                Debug.Log("ScatterRooms done, room_rects.Count = " + room_rects.Count);
                //DrawMapByRects(room_rects, room_rects_color);
                //DrawWalls();
            }

            yield return tm.YieldOrDelay(cfg.stepDelay);

            // Step 3: Combine overlapping rooms
            BottomBanner.Show("Locate Discrete rooms...");
            if (cfg.useCellularAutomata) // locate rooms from cellular automata
            {
                BottomBanner.Show("Remove tiny rocks...");
                yield return StartCoroutine(RemoveTinyRocksCoroutine(tm: null));

                // For Cellular Automata, find rooms from the map
                BottomBanner.Show("Locate Discrete rooms...");
                yield return StartCoroutine(FindClustersCoroutine(map, FLOOR, rooms, tm: null));

                BottomBanner.Show("Remove tiny rooms...");
                yield return StartCoroutine(RemoveTinyRoomsCoroutine(tm: null));
            }
            if (cfg.useScatterRooms)
            {
                BottomBanner.Show("Convert all Rects to Rooms...");
                rooms = ConvertAllRectToRooms(room_rects, room_rects_color, SetTile: true);
                DrawMapByRooms(rooms);
                DrawWalls();
                if (tm.IfYield()) yield return null;     // cooperative yield decision

                yield return tm.YieldOrDelay(cfg.stepDelay);
                // Step 4: Merge overlapping rooms
                BottomBanner.Show("Merging Overlapping Rooms...");
                if (cfg.MergeScatteredRooms)
                    rooms = MergeOverlappingRooms(rooms, considerAdjacency: true, eightWay: false);
                DrawMapByRooms(rooms);
                DrawWalls();
                yield return tm.YieldOrDelay(cfg.stepDelay); // depends on cfg.showBuildProcess
            }

            if (cfg.perlinFloorHeights > 0)
            {
                for (int r = 0; r < rooms.Count; r++)
                {
                    //int setHeight = rooms[r].heights[0];
                    rooms[r] = AddPerlinToFloorHeights(rooms[r]);
                }
            }
            
            // ======== End Rooms, Begin Corridors ========
            if (cfg.useCellularAutomata || cfg.useScatterRooms)
            {
                DrawMapByRooms(rooms);
                DrawWalls();

                // Step 5: Connect rooms with corridors
                BottomBanner.Show("Connecting Rooms with Corridors...");
                yield return StartCoroutine(ConnectRoomsByCorridors(tm: null));

                DrawMapByRooms(rooms);
                DrawWalls();
                yield return tm.YieldOrDelay(cfg.stepDelay);
            }

            BottomBanner.Show("Building Wall Lists...");
            yield return null;
            yield return BuildWallsAroundFloorsInRooms(tm: null);

            BottomBanner.Show("Height Map Build...");
            yield return null;
            // FillVoidToWalls(map);
            yield return StartCoroutine(Build3DFromRooms(tm: null));
            // If Build should be static, change its definition to 'public static void Build(...)' in HeightMap3DBuilder.

            yield return tm.YieldOrDelay(cfg.stepDelay);

            BottomBanner.ShowFor("Dungeon generation complete!", 5f);
        }
        finally { if (local_tm) tm.End(); }

        TimeManager.Instance.DumpStats();
    }

    // UNCHANGED
    List<Room> ConvertAllRectToRooms(List<RectInt> room_rects, List<Color> room_rects_color, bool SetTile)
    {
        List<Vector2Int> PointsList;
        List<int> HeightsList = new();
        List<Room> rooms = new List<Room>();
        Debug.Log("Converting " + room_rects.Count + " Rects to Rooms...");
        for (int i = 0; i < room_rects.Count; i++)
        {
            var room_rect = room_rects[i];
            var room_rect_color = room_rects_color[i];
            var room_rect_height = room_rects_heights[i];
            PointsList = ConvertRectToRoomPoints(room_rect, room_rect_color, false/*SetTile*/);
            HeightsList = new();
            for (int h = 0; h < PointsList.Count; h++) HeightsList.Add(room_rect_height);
            //Debug.Log($"Room {i}: Room points = {PointsList.Count}, Room heights = {HeightsList.Count}");
            Room room = new Room(PointsList, HeightsList);
            room.isCorridor = false;
            room.name = "Room " + (rooms.Count + 1);
            room.setColorFloor(room_rect_color);
            rooms.Add(room);
            //DrawMapByRooms(rooms);
            //Debug.Log($"ConvertRectsToRooms: room {i} height = {room.cells[0].height}");
        }
        return rooms;
    }

    // UNCHANGED
    // ConvertRectToRoomPoints generates a list of points within the
    //  given room rectangle or oval.
    // As a side effect, it can also set the corresponding tiles in the tilemap.
    List<Vector2Int> ConvertRectToRoomPoints(RectInt room_rect, Color room_rect_color, bool SetTile)
    {
        //BottomBanner.Show($"Measuring rooms...");
        List<Vector2Int> roomPoints = new List<Vector2Int>();
        for (int x = room_rect.xMin; x < room_rect.xMax; x++)
        {
            for (int y = room_rect.yMin; y < room_rect.yMax; y++)
            {
                if (IsPointInRoomRectOrOval(new Vector2Int(x, y), room_rect))
                {
                    roomPoints.Add(new Vector2Int(x, y));
                    if (SetTile)
                    {
                        tilemap.SetTile(new Vector3Int(x, y, 0), floorTile);
                        tilemap.SetTileFlags(new Vector3Int(x, y, 0), TileFlags.None); // Allow color changes
                        tilemap.SetColor(new Vector3Int(x, y, 0), room_rect_color); // Set default color
                    }
                }
            }
        }
        return roomPoints;
    }

    // UNUSED
    public void DrawMapByRects(List<RectInt> room_rects, List<Color> colors)
    {
        for (int i = 0; i < room_rects.Count; i++)
        {
            var room_rect = room_rects[i];
            var color = colors[i];
            //("Drawing Rect " + room_rect);
            DrawRect(room_rect, color);
        }
    }

    public void DrawRect(RectInt room_rect, Color tempcolor)
    {
        //Debug.Log("Drawing Rect ");
        for (int x = room_rect.xMin; x < room_rect.xMax; x++)
        {
            for (int y = room_rect.yMin; y < room_rect.yMax; y++)
            {
                if (IsPointInRoomRectOrOval(new Vector2Int(x, y), room_rect))
                {
                    tilemap.SetTile(new Vector3Int(x, y, 0), floorTile);
                    tilemap.SetTileFlags(new Vector3Int(x, y, 0), TileFlags.None); // Allow color changes
                    tilemap.SetColor(new Vector3Int(x, y, 0), tempcolor);

                    map[x, y] = FLOOR;
                }
            }
        }
    }

    // NEW
    public void DrawMapByRooms(List<Room> rooms, bool clearscreen = true)
    {
        Debug.Log("Drawing Map by " + rooms.Count + " rooms...");
        if (clearscreen) tilemap.ClearAllTiles();

        foreach (var room in rooms)
        {
            // OLD_VERSION
            //Debug.Log("Drawing " + room.Name + " size: " + room.tiles.Count);
            //            foreach (var point in room.tiles)
            //            {
            //                if (!clearscreen) tilemap.SetTile(new Vector3Int(point.x, point.y, 0), null); // clear old tile
            //                tilemap.SetTile(new Vector3Int(point.x, point.y, 0), floorTile);
            //                tilemap.SetTileFlags(new Vector3Int(point.x, point.y, 0), TileFlags.None); // Allow color changes
            //                tilemap.SetColor(new Vector3Int(point.x, point.y, 0), room.colorFloor); // Set room color
            //
            //                map[point.x, point.y] = FLOOR;
            //                mapHeights[point.x, point.y] = GetHeightOfLocationFromAllRooms(rooms, point);
            //            }
            // CELL_VERSION
            //Debug.Log("Drawing " + room.Name + " size: " + room.tiles.Count);
            foreach (var cell in room.cells)
            {
                Vector3Int pos3 = cell.pos3d;
                pos3.z = 0; // need (x,y,0) for SetTile
                if (!clearscreen) tilemap.SetTile(pos3, null); // clear old tile
                tilemap.SetTile(pos3, floorTile);
                tilemap.SetTileFlags(pos3, TileFlags.None); // Allow color changes
                tilemap.SetColor(pos3, cell.colorFloor); // Set room color
                                                         //
                map[cell.x, cell.y] = FLOOR;
                mapHeights[cell.x, cell.y] = cell.height;
            }
        }
    }

    // NEW    
    public Room DrawCorridorSloped(Vector2Int start, Vector2Int end, int start_height, int end_height, int start_room, int end_room)
    {
        List<Vector2Int> path;
        HashSet<Vector2Int> hashPath = new();
        HashSet<Vector2Int> neighbor_start_hashPath = new();
        HashSet<Vector2Int> neighbor_end_hashPath = new();
        Room room = new();

        switch (cfg.TunnelsAlgorithm)
        {
            case DungeonSettings.TunnelsAlgorithm_e.TunnelsOrthogonal:
                BottomBanner.Show("Drawing orthogonal ..");
                path = OrthogonalLine(start, end);
                break;
            case DungeonSettings.TunnelsAlgorithm_e.TunnelsStraight:
                BottomBanner.Show("Drawing straight ..");
                path = BresenhamLine(start, end);
                break;
            case DungeonSettings.TunnelsAlgorithm_e.TunnelsOrganic:
                BottomBanner.Show("Drawing organic ..");
                path = OrganicLine(start, end);
                break;
            case DungeonSettings.TunnelsAlgorithm_e.TunnelsCurved:
                BottomBanner.Show("Drawing curved ..");
                path = BezierLine(start, end);
                break;
            default:
                BottomBanner.Show("Drawing Noisy Bresenham ..");
                path = NoisyBresenhamLine(start, end);
                break;
        }

        int path_length = path.Count;
        if (path_length <= 1)
        {
            //Debug.Log($"path_length = {path_length}, must be > 1");
            //TODO: make a vertical ladder?
            return (room); // empty room
        }
        float delta_h = (float)(end_height - start_height) / (float)(path_length - 1);
        // pre-seed the hashPath with both end rooms so we don't add corridor tiles there.

        foreach (Cell cell in rooms[start_room].cells)
            neighbor_start_hashPath.Add(cell.pos);
        foreach (Cell cell in rooms[end_room].cells)
            neighbor_end_hashPath.Add(cell.pos);

        if (cfg.limit_slope && (Math.Abs(delta_h) > 1f))
        {
            Debug.Log($"Slope of corridor is too great Abs({delta_h}) > 1");
            delta_h = Math.Clamp(delta_h, -1f, 1f); // Don't allow ramps too steep to climb.
            // Should we generate a new corridor that is longer? TODO
        }

        //Debug.Log("Drawing corridor length " + path.Count + " from " + start + " to " + end + " width " + cfg.corridorWidth + " using " + cfg.TunnelsAlgorithm);
        //Debug.Log("Corridor: start_height=" + start_height + " end_height=" + end_height + " length=" + path_length);
        int brush_neg = -cfg.corridorWidth / 2;
        int brush_pos = brush_neg + cfg.corridorWidth;

        //foreach (Vector2Int point in path)
        for (int i = 0; i < path.Count; i++)
        {
            Vector2Int point = path[i];
            int height = start_height + (int)Math.Round(i * delta_h);
            // Square brush around each line point
            for (int dx = brush_neg; dx < brush_pos; dx++)
            {
                for (int dy = brush_neg; dy < brush_pos; dy++)
                {
                    // At both endpoints, only use centerpoint of brush.
                    // Going beyond this can make odd transitions.
                    if ((i == 0 || i == path.Count - 1) && ((dx != 0) || (dy != 0)))
                        continue;

                    Vector3Int tilePos3d = new Vector3Int(point.x + dx, point.y + dy, 0);
                    if (tilePos3d.x < 0 || tilePos3d.x >= cfg.mapWidth || tilePos3d.y < 0 || tilePos3d.y >= cfg.mapHeight)
                    {
                        continue; // Skip out-of-bounds tiles
                    }
                    tilemap.SetTile(tilePos3d, floorTile);

                    Vector2Int tilePos2 = new Vector2Int(tilePos3d.x, tilePos3d.y);

                    // Keep highest point
                    //bool overlap = false;
                    int neighborheight;
                    height = CalculateRampHeightFromPosition(tilePos2, start, end, start_height, end_height);

                    if (!hashPath.Contains(tilePos2))
                    {
                        // check if neighbor overlap.  If so, remove from neighbor.
                        if (neighbor_start_hashPath.Contains(tilePos2))
                        {
                            //overlap = true;
                            neighborheight = rooms[start_room].GetHeightInRoom(tilePos2);
                            if (((neighborheight - height) > 0) && ((neighborheight - height) < 30))
                            {
                                // punch hole in ceiling of start_room
                                int cell_num = rooms[start_room].GetCellInRoom(tilePos2);
                                rooms[start_room].cells.RemoveAt(cell_num);
                                rooms[start_room].ResetCellDictionary();
                            }
                        }
                        if (neighbor_end_hashPath.Contains(tilePos2))
                        {
                            //overlap = true;
                            neighborheight = rooms[end_room].GetHeightInRoom(tilePos2);
                            if (((neighborheight - height) > 0) && ((neighborheight - height) < 30))
                            {
                                // punch hole in ceiling of end_room
                                int cell_num = rooms[end_room].GetCellInRoom(tilePos2);
                                rooms[end_room].cells.RemoveAt(cell_num);
                                rooms[end_room].ResetCellDictionary();
                            }
                        }
                    }
                    // Add the corridor cell
                    room.cells.Add(new Cell(tilePos2.x, tilePos2.y, height));
                }
            }
        }
        room.isCorridor = true;
        return room;
    }

    // based on distances from both ends, calculate height.
    // problem: past the ends, height goes down.  TODO: better algorithm.
    int CalculateRampHeightFromPosition(Vector2Int target, Vector2Int start, Vector2Int end, int start_height, int end_height)
    {
        float target_to_start;
        float target_to_end;
        float pct_distance;

        Vector2Int delta;
        float target_height;

        delta = (target - start);
        target_to_start = (float)Math.Sqrt(delta.sqrMagnitude);
        delta = (target - end);
        target_to_end = (float)Math.Sqrt(delta.sqrMagnitude);
        pct_distance = target_to_start / (target_to_start + target_to_end);

        target_height = (end_height - start_height) * pct_distance + start_height;
        return (int)Math.Round(target_height);
    }

    public void DrawWalls()  // from tilemap, adds walls to the existing 2D tilemap
    {
        BoundsInt bounds = tilemap.cellBounds;
        //BottomBanner.Show("Drawing walls...");
        for (int x = bounds.xMin - 1; x <= bounds.xMax + 1; x++)
        {
            for (int y = bounds.yMin - 1; y <= bounds.yMax + 1; y++)
            {
                Vector3Int pos = new(x, y, 0);
                if (tilemap.GetTile(pos) == floorTile)
                    continue;                       // Skip floor tiles
                if (HasFloorNeighbor(pos))
                    tilemap.SetTile(pos, wallTile); // add wall tile
                else
                    tilemap.SetTile(pos, null);     // Remove wall if no floor neighbor
            }
        }
    }

    // UNUSED
    // Check if a tile at position pos has a neighboring floor tile within the specified radius
    bool HasFloorNeighbor(Vector3Int pos, int radius = 1)
    {
        if (tilemap == null || floorTile == null) return false; // Safety check

        // Check all neighbors within the specified radius
        NeighborCache.Shape shape = cfg.neighborShape;
        bool includeDiagonals = cfg.includeDiagonals;
        var neighbors = NeighborCache.Get(radius, shape, borderOnly: true, includeDiagonals);

        foreach (var offset in neighbors)
        {
            Vector3Int neighborPos = pos + offset;
            if (tilemap.GetTile(neighborPos) == floorTile)
            {
                return true; // Found a floor tile neighbor
            }
        }
        return false; // No floor tile neighbors found
    }

    bool IsPointInRoomRectOrOval(Vector2Int point, RectInt room_rect)
    {
        // start by checking the rectangular bounds
        bool isInRect = (point.x >= room_rect.xMin && point.x < room_rect.xMax
                        && point.y >= room_rect.yMin && point.y < room_rect.yMax);

        if (!isInRect) return false; // outside rectangular bounds for either shape
        if (cfg.ovalRooms == false) return true; // inside rectangular room bounds

        // Check if the point is within the ellipse defined by the room
        float centerX = room_rect.xMin + room_rect.width / 2f;
        float centerY = room_rect.yMin + room_rect.height / 2f;
        float radiusX = room_rect.width / 2f;
        float radiusY = room_rect.height / 2f;

        return Mathf.Pow((point.x - centerX) / radiusX, 2) + Mathf.Pow((point.y - centerY) / radiusY, 2) <= 1;
    }

    // point bounds checking for rectangular or oval world maps
    public bool IsPointInWorld(Vector2Int point)
    {
        if (point.x < 0 || point.y < 0 ||
            point.x > cfg.mapWidth || point.y > cfg.mapHeight)
            return false; // out of the world
        if (!cfg.roundWorld) return true; // square world, limits are sufficient

        // Round world (axis-aligned ellipse) inscribed in the map.
        Vector2 Cw = new Vector2(cfg.mapWidth * 0.5f, cfg.mapHeight * 0.5f);
        float margin = 0.5f; // hardcoded
        float Rx = cfg.mapWidth * 0.5f - margin;
        float Ry = cfg.mapHeight * 0.5f - margin;
        float Rx2 = Rx * Rx, Ry2 = Ry * Ry;
        float dx = point.x - Cw.x, dy = point.y - Cw.y;
        return ((dx * dx) / Rx2 + (dy * dy) / Ry2) <= 1f; // <= 1 means inside world ellipse
    }

    // Returns true if the proposed room bounds fit inside the world according to config flags.
    // (1) cfg.ovalRooms   — RectInt room treated as an inscribed axis-aligned ellipse when true.
    // (2) cfg.roundWorld — world bounds are an axis-aligned ellipse inscribed in the map when true;
    //                       otherwise world is the rectangular map.
    // "samples" controls boundary sampling for oval-in-oval; "margin" shrinks world a bit to avoid edge bleed.
    // 
    // Works for: Rect in Rect, Oval in Rect, Rect in Oval, and Oval in Oval.
    public bool RoomFitsWorld(RectInt roomRect, int samples = 32, float margin = 0.5f)
    {
        // Quick early-reject: roomRect must at least fit inside the map rectangle.
        // works for all room shapes and map shapes.
        if (roomRect.xMin < 0 || roomRect.yMin < 0 ||
                    roomRect.xMax > cfg.mapWidth || roomRect.yMax > cfg.mapHeight)
            return false;

        // Any shape in a rectangular world:
        if (!cfg.roundWorld)
        {
            return true; // already proved it fits the map rectangle
        }

        // Round world (axis-aligned ellipse) inscribed in the map.
        Vector2 Cw = new Vector2(cfg.mapWidth * 0.5f, cfg.mapHeight * 0.5f);
        float Rx = cfg.mapWidth * 0.5f - margin;
        float Ry = cfg.mapHeight * 0.5f - margin;
        float Rx2 = Rx * Rx, Ry2 = Ry * Ry;

        float UnitCircle(Vector2 p)
        {
            float dx = p.x - Cw.x, dy = p.y - Cw.y;
            return (dx * dx) / Rx2 + (dy * dy) / Ry2; // <= 1 means inside world ellipse
        }

        if (cfg.ovalRooms) // oval room in oval world:
        {
            // Room is an axis-aligned ellipse inscribed in the rect
            Vector2 Cr = new Vector2(roomRect.xMin + roomRect.width * 0.5f,
                                    roomRect.yMin + roomRect.height * 0.5f);
            float rx = roomRect.width * 0.5f;
            float ry = roomRect.height * 0.5f;

            // Sample boundary n times, reject on any violation
            for (int i = 0; i < samples; i++)
            {
                float t = (2f * Mathf.PI * i) / samples;
                Vector2 p = Cr + new Vector2(rx * Mathf.Cos(t), ry * Mathf.Sin(t));
                if (UnitCircle(p) > 1f) return false;
            }
            return true;
        }
        else // rectangular room in oval world:
        {
            // Room is a rectangle: checking corners is exact for axis-aligned containment in an ellipse space
            float cx = roomRect.xMin + roomRect.width * 0.5f;
            float cy = roomRect.yMin + roomRect.height * 0.5f;
            float hx = roomRect.width * 0.5f;
            float hy = roomRect.height * 0.5f;

            Vector2 c1 = new Vector2(cx - hx, cy - hy);
            Vector2 c2 = new Vector2(cx + hx, cy - hy);
            Vector2 c3 = new Vector2(cx - hx, cy + hy);
            Vector2 c4 = new Vector2(cx + hx, cy + hy);

            return UnitCircle(c1) <= 1f && UnitCircle(c2) <= 1f &&
                UnitCircle(c3) <= 1f && UnitCircle(c4) <= 1f;
        }
    }

    // UNUSED
    void GenerateWallLists()
    {
        //List<Vector2Int> wall_list_room;
        //HashSet<Vector2Int> new_wall_hash;

        // TODO: replace with directions in Room.cs
        Vector2Int[] directions = {
            Vector2Int.up, Vector2Int.down,
            Vector2Int.left, Vector2Int.right
        };

        for (int room_number = 0; room_number < rooms.Count; room_number++)
        {
            //wall_list_room = new();
            //new_wall_hash = new();
            foreach (Cell cell in rooms[room_number].cells)
            {
                Vector2Int pos = cell.pos;
                foreach (Vector2Int dir in directions)
                {
                    // look in dir, if not in room then consider it a wall and
                    ///  set appropriate wall direction flag.
                    if (rooms[room_number].GetCellInRoom(pos + dir) == -1) // non-existance check.
                    {
                        DirFlags dir_flag = DirFlagsEx.FromVector2Int(dir);
                        cell.walls |= dir_flag;

                        // Debug to map display:
                        Vector3Int pos3d = cell.pos3d;
                        pos3d.z = 0;
                        tilemap.SetTile(pos3d, wallTile);
                        tilemap.SetTileFlags(pos3d, TileFlags.None);
                        tilemap.SetColor(pos3d, Color.red);
                        //Debug.Log($"Wall found in direction {dir.x},{dir.y}; flags + {dir_flag} = {cell.walls}");
                    }
                }
                //Debug.Log($"walls = {cell.walls}");
            }
        }
    }

    // uses map[,]
    public void FillVoidToWalls(byte[,] map)
    {
        for (var y = 0; y < cfg.mapHeight; y++)
            for (var x = 0; x < cfg.mapWidth; x++)
            {
                if (map[x, y] == 0) map[x, y] = WALL;
            }
    }

    // NEW
    /// <summary>
    /// Merge rooms that overlap (share at least one tile).
    /// If considerAdjacency is true, rooms that touch by edge/corner are merged too.
    /// </summary>
    /// <param name="rooms">Input rooms (each has List<Vector2Int> tiles)</param>
    /// <param name="considerAdjacency">If true, merge when tiles are neighbors (4- or 8-connected)</param>
    /// <param name="eightWay">If adjacency is considered, choose 4-way or 8-way</param>
    public static List<Room> MergeOverlappingRooms(List<Room> rooms, bool considerAdjacency = false, bool eightWay = true)
    {
        //BottomBanner.Show("Merging overlapping rooms...");
        if (rooms == null || rooms.Count == 0) return new List<Room>();

        var dsu = new DSU(rooms.Count);
        var owner = new Dictionary<Vector2Int, int>(1024);

        // Optional neighbor offsets for adjacency merging
        Vector2Int[] n4 = new[]
        {
            new Vector2Int( 1, 0),
            new Vector2Int(-1, 0),
            new Vector2Int( 0, 1),
            new Vector2Int( 0,-1)
        };
        Vector2Int[] n8 = new[]
        {
            new Vector2Int( 1, 0), new Vector2Int(-1, 0), new Vector2Int(0, 1), new Vector2Int(0,-1),
            new Vector2Int( 1, 1), new Vector2Int( 1,-1), new Vector2Int(-1, 1), new Vector2Int(-1,-1)
        };
        var neighbors = eightWay ? n8 : n4;

        // 1) Scan all tiles, union rooms that share tiles (overlap)
        for (int i = 0; i < rooms.Count; i++)
        {
            var cells = rooms[i].cells;
            for (int k = 0; k < cells.Count; k++)
            {
                var t = cells[k].pos;

                if (!owner.TryGetValue(t, out int j))
                {
                    owner[t] = i; // first time we see this tile, claim it
                }
                else
                {
                    // tile already owned by room j => overlap with i
                    dsu.Union(i, j);
                }

                // 2) Optional: adjacency-based merging (touching rooms)
                if (considerAdjacency)
                {
                    foreach (var d in neighbors)
                    {
                        var n = t + d;
                        if (owner.TryGetValue(n, out int kOwner))
                            dsu.Union(i, kOwner);
                    }
                }
            }
        }

        // 3) Fold tiles into their root groups while PRESERVING order and height pairing
        var groupedTiles = new Dictionary<int, List<Vector2Int>>();
        var groupedHeights = new Dictionary<int, List<int>>();
        var groupedSeen = new Dictionary<int, HashSet<Vector2Int>>();

        for (int i = 0; i < rooms.Count; i++)
        {
            int root = dsu.Find(i);
            if (!groupedTiles.ContainsKey(root))
            {
                groupedTiles[root] = new List<Vector2Int>(rooms[i].cells.Count);
                groupedHeights[root] = new List<int>(rooms[i].cells.Count);
                groupedSeen[root] = new HashSet<Vector2Int>();
            }

            //var rTiles = rooms[i].GetTilesList();     // not a created function
            //var rHeights = rooms[i].GetHeightsList();
            var rCells = rooms[i].cells;

            for (int k = 0; k < rooms[i].cells.Count; k++)
            {
                var t = rCells[k].pos;
                var h = rCells[k].height;
                if (!groupedSeen[root].Add(t))
                    continue; // skip duplicates while preserving first-seen order

                groupedTiles[root].Add(t);
                groupedHeights[root].Add(h);
            }
        }

        // 4) Emit merged rooms with preserved tile/height order
        var merged = new List<Room>(groupedTiles.Count);
        foreach (var root in groupedTiles.Keys)
        {
            var newRoom = new Room(groupedTiles[root], groupedHeights[root]);
            newRoom.setColorFloor(highlight: true);
            merged.Add(newRoom);
        }

        // (Optional) sort by size descending like your existing code
        merged.Sort((a, b) => b.Size.CompareTo(a.Size));
        return merged;
    }

    // global variables for return of success and failure results
    [HideInInspector] public bool success;    // global generic return value from various tasks
    [HideInInspector] public string failure;    // global failure description string
    

    // =======================================================
    // helper routines
    // =======================================================
    //  Extra functions

    public String ListOfIntToString(List<int> ilist, bool do_sort = true)
    {
        String result = "List: ";
        if (do_sort) ilist.Sort();
        foreach (int i in ilist)
        {
            result = result + i + ",";
        }
        return result;
    }

    public Vector2Int[] directions_xy = { Vector2Int.up,
                                   Vector2Int.down,
                                   Vector2Int.left,
                                   Vector2Int.right, };
                            //       Vector2Int.up + Vector2Int.left,
                            //       Vector2Int.up + Vector2Int.right,
                            //       Vector2Int.down + Vector2Int.left,
                            //       Vector2Int.down + Vector2Int.right };

    public Color getColor(Color? color = null, bool highlight = true, string rgba = "")
    {
        Color colorrgba = new(); //temp
        Color return_color = Color.white;

        if (color != null)
            return_color = (Color)color;
        else if ((!string.IsNullOrEmpty(rgba)) && (ColorUtility.TryParseHtmlString(rgba, out colorrgba)))
            return_color = colorrgba;
        else if (highlight)
            return_color = UnityEngine.Random.ColorHSV(0f, 1f, 0.6f, 1f, 0.6f, 1f);   // Bright Random
        else // highlight == false
            return_color = UnityEngine.Random.ColorHSV(0f, 1f, 0.6f, 1f, 0.1f, 0.4f); // Dark Random

        return return_color;
    }

}
//} // End class DungeonGenerator

// ================================================= //

//public static class DSU
//
// Simple Union-Find/Disjoint Set (DSU=Disjoint Set Union)
// Created by ChatGPT, for MergeOverlappingRooms function.
// Will probably re-write this using existing hashes.
class DSU
{
    int[] parent;
    int[] rank;

    public DSU(int n)
    {
        parent = new int[n];
        rank = new int[n];
        for (int i = 0; i < n; i++) parent[i] = i;
    }

    public int Find(int x)
    {
        if (parent[x] != x) parent[x] = Find(parent[x]);
        return parent[x];
    }

    public void Union(int a, int b)
    {
        a = Find(a); b = Find(b);
        if (a == b) return;
        if (rank[a] < rank[b]) parent[a] = b;
        else if (rank[a] > rank[b]) parent[b] = a;
        else { parent[b] = a; rank[a]++; }
    }
}